apiVersion: v2
name: kubevirtbmc
version: 0.5.0
description: A Helm chart for KubeVirtBMC
type: application
keywords:
- kubevirt
- cdi
- vm
- bmc
- ipmi
- redfish
home: https://kubevirtbmc.io
sources:
- https://github.com/kubevirtbmc/kubevirtbmc
maintainers:
- name: starbops
  email: starbops@zespre.com
  url: https://www.zespre.com
- name: anishbista60
  email: anishbista60@gmail.com
appVersion: v0.8.0
