apiVersion: v2
name: kubevirtbmc
version: 0.4.1
description: A Helm chart for KubeVirtBMC
type: application
keywords:
- kubevirt
- cdi
- vm
- bmc
- ipmi
- redfish
home: https://kubevirtbmc.io
sources:
- https://github.com/kubevirtbmc/kubevirtbmc
maintainers:
- name: starbops
  email: starbops@hey.com
  url: https://www.zespre.com
appVersion: v0.7.1
