version: "2"
run:
  allow-parallel-runners: true

linters:
  default: standard

  settings:
    staticcheck:
      dot-import-whitelist:
        - github.com/onsi/gomega
        - github.com/onsi/ginkgo/v2

  exclusions:
    generated: lax
    rules:
      - linters:
          - lll
        path: api/*
      - linters:
          - dupl
          - lll
        path: internal/*
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
