// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/resourcemanager/resourcemanager.go
//
// Generated by this command:
//
//	mockgen -source=pkg/resourcemanager/resourcemanager.go -destination=pkg/resourcemanager/mock_resourcemanager.go -package=resourcemanager
//

// Package resourcemanager is a generated GoMock package.
package resourcemanager

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	v1beta1 "kubevirt.io/kubevirtbmc/api/bmc/v1beta1"
)

// MockResourceManager is a mock of ResourceManager interface.
type MockResourceManager struct {
	ctrl     *gomock.Controller
	recorder *MockResourceManagerMockRecorder
	isgomock struct{}
}

// MockResourceManagerMockRecorder is the mock recorder for MockResourceManager.
type MockResourceManagerMockRecorder struct {
	mock *MockResourceManager
}

// NewMockResourceManager creates a new mock instance.
func NewMockResourceManager(ctrl *gomock.Controller) *MockResourceManager {
	mock := &MockResourceManager{ctrl: ctrl}
	mock.recorder = &MockResourceManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResourceManager) EXPECT() *MockResourceManagerMockRecorder {
	return m.recorder
}

// ClearBootOverrides mocks base method.
func (m *MockResourceManager) ClearBootOverrides(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearBootOverrides", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearBootOverrides indicates an expected call of ClearBootOverrides.
func (mr *MockResourceManagerMockRecorder) ClearBootOverrides(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearBootOverrides", reflect.TypeOf((*MockResourceManager)(nil).ClearBootOverrides), ctx)
}

// EjectMedia mocks base method.
func (m *MockResourceManager) EjectMedia(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EjectMedia", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// EjectMedia indicates an expected call of EjectMedia.
func (mr *MockResourceManagerMockRecorder) EjectMedia(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EjectMedia", reflect.TypeOf((*MockResourceManager)(nil).EjectMedia), ctx)
}

// ForcePowerCycle mocks base method.
func (m *MockResourceManager) ForcePowerCycle(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForcePowerCycle", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ForcePowerCycle indicates an expected call of ForcePowerCycle.
func (mr *MockResourceManagerMockRecorder) ForcePowerCycle(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForcePowerCycle", reflect.TypeOf((*MockResourceManager)(nil).ForcePowerCycle), ctx)
}

// ForcePowerOff mocks base method.
func (m *MockResourceManager) ForcePowerOff(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForcePowerOff", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ForcePowerOff indicates an expected call of ForcePowerOff.
func (mr *MockResourceManagerMockRecorder) ForcePowerOff(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForcePowerOff", reflect.TypeOf((*MockResourceManager)(nil).ForcePowerOff), ctx)
}

// GetBootFlags mocks base method.
func (m *MockResourceManager) GetBootFlags(ctx context.Context) (*BootFlagsState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBootFlags", ctx)
	ret0, _ := ret[0].(*BootFlagsState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBootFlags indicates an expected call of GetBootFlags.
func (mr *MockResourceManagerMockRecorder) GetBootFlags(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBootFlags", reflect.TypeOf((*MockResourceManager)(nil).GetBootFlags), ctx)
}

// GetBootOverride mocks base method.
func (m *MockResourceManager) GetBootOverride(ctx context.Context) (*v1beta1.BootOverrideStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBootOverride", ctx)
	ret0, _ := ret[0].(*v1beta1.BootOverrideStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBootOverride indicates an expected call of GetBootOverride.
func (mr *MockResourceManagerMockRecorder) GetBootOverride(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBootOverride", reflect.TypeOf((*MockResourceManager)(nil).GetBootOverride), ctx)
}

// GetComputerSystem mocks base method.
func (m *MockResourceManager) GetComputerSystem(ctx context.Context) (ComputerSystemInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComputerSystem", ctx)
	ret0, _ := ret[0].(ComputerSystemInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComputerSystem indicates an expected call of GetComputerSystem.
func (mr *MockResourceManagerMockRecorder) GetComputerSystem(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComputerSystem", reflect.TypeOf((*MockResourceManager)(nil).GetComputerSystem), ctx)
}

// GetManager mocks base method.
func (m *MockResourceManager) GetManager(ctx context.Context) (ManagerInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetManager", ctx)
	ret0, _ := ret[0].(ManagerInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetManager indicates an expected call of GetManager.
func (mr *MockResourceManagerMockRecorder) GetManager(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetManager", reflect.TypeOf((*MockResourceManager)(nil).GetManager), ctx)
}

// GetPowerStatus mocks base method.
func (m *MockResourceManager) GetPowerStatus(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPowerStatus", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPowerStatus indicates an expected call of GetPowerStatus.
func (mr *MockResourceManagerMockRecorder) GetPowerStatus(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPowerStatus", reflect.TypeOf((*MockResourceManager)(nil).GetPowerStatus), ctx)
}

// GetSystemSerial mocks base method.
func (m *MockResourceManager) GetSystemSerial(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSystemSerial", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSystemSerial indicates an expected call of GetSystemSerial.
func (mr *MockResourceManagerMockRecorder) GetSystemSerial(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSystemSerial", reflect.TypeOf((*MockResourceManager)(nil).GetSystemSerial), ctx)
}

// GetSystemUUID mocks base method.
func (m *MockResourceManager) GetSystemUUID(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSystemUUID", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSystemUUID indicates an expected call of GetSystemUUID.
func (mr *MockResourceManagerMockRecorder) GetSystemUUID(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSystemUUID", reflect.TypeOf((*MockResourceManager)(nil).GetSystemUUID), ctx)
}

// GetVirtualMedia mocks base method.
func (m *MockResourceManager) GetVirtualMedia(ctx context.Context) (VirtualMediaInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVirtualMedia", ctx)
	ret0, _ := ret[0].(VirtualMediaInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVirtualMedia indicates an expected call of GetVirtualMedia.
func (mr *MockResourceManagerMockRecorder) GetVirtualMedia(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVirtualMedia", reflect.TypeOf((*MockResourceManager)(nil).GetVirtualMedia), ctx)
}

// InsertMedia mocks base method.
func (m *MockResourceManager) InsertMedia(ctx context.Context, image string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertMedia", ctx, image)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertMedia indicates an expected call of InsertMedia.
func (mr *MockResourceManagerMockRecorder) InsertMedia(ctx, image any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertMedia", reflect.TypeOf((*MockResourceManager)(nil).InsertMedia), ctx, image)
}

// PowerCycle mocks base method.
func (m *MockResourceManager) PowerCycle(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PowerCycle", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// PowerCycle indicates an expected call of PowerCycle.
func (mr *MockResourceManagerMockRecorder) PowerCycle(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PowerCycle", reflect.TypeOf((*MockResourceManager)(nil).PowerCycle), ctx)
}

// PowerOff mocks base method.
func (m *MockResourceManager) PowerOff(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PowerOff", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// PowerOff indicates an expected call of PowerOff.
func (mr *MockResourceManagerMockRecorder) PowerOff(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PowerOff", reflect.TypeOf((*MockResourceManager)(nil).PowerOff), ctx)
}

// PowerOn mocks base method.
func (m *MockResourceManager) PowerOn(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PowerOn", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// PowerOn indicates an expected call of PowerOn.
func (mr *MockResourceManagerMockRecorder) PowerOn(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PowerOn", reflect.TypeOf((*MockResourceManager)(nil).PowerOn), ctx)
}

// SetBootDevice mocks base method.
func (m *MockResourceManager) SetBootDevice(ctx context.Context, device BootDevice, opts *BootOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBootDevice", ctx, device, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBootDevice indicates an expected call of SetBootDevice.
func (mr *MockResourceManagerMockRecorder) SetBootDevice(ctx, device, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBootDevice", reflect.TypeOf((*MockResourceManager)(nil).SetBootDevice), ctx, device, opts)
}

// SetFirmwareMode mocks base method.
func (m *MockResourceManager) SetFirmwareMode(ctx context.Context, mode FirmwareMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFirmwareMode", ctx, mode)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetFirmwareMode indicates an expected call of SetFirmwareMode.
func (mr *MockResourceManagerMockRecorder) SetFirmwareMode(ctx, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFirmwareMode", reflect.TypeOf((*MockResourceManager)(nil).SetFirmwareMode), ctx, mode)
}
